- projects/server/package.json
dependencies back-end:
bycript
express validator
handlebars
multer
mysql2
nodemailer
sequelize
> Update dependencies back-end:

- package-lock.json
- projects/client/package.json
Front-end dependencies installed: 
- chakra ui
- chakra icons
- react redux
- reduxjs toolkit
- formik
- yup
- react icons
- embla carousel
> OGWA-FE-DEPENDENCIES

- package-lock.json
- projects/server/src/config/config.js
- projects/server/src/controllers/adminControllers.js
- projects/server/src/controllers/authControllers.js
- projects/server/src/controllers/index.js
- projects/server/src/controllers/productControllers.js
- projects/server/src/index.js
- projects/server/src/middleware/auth.js
- projects/server/src/middleware/multer.js
- projects/server/src/middleware/transporter.js
- projects/server/src/middleware/validator.js
- projects/server/src/models/Categories.js
- projects/server/src/models/Products.js
- projects/server/src/models/index.js
- projects/server/src/routers/authRouters.js
- projects/server/src/routers/index.js
- projects/server/src/routers/productRouters.js
- Added implicit folders
- Edited main config to accommodate dotenv
- Database configuration
> Various server initializations, added implicit folders, edited main config to accommodate dotenv, database configuration

- projects/client/src/pages/verification.jsx
- projects/client/src/routes/index.jsx
- projects/client/src/views/Verification/index.jsx
- projects/server/src/controllers/userControllers.js
- projects/server/src/routers/userRouters.js
As a user, I want to be able to verify my account
> [OGWA-13] As a user, I want to be able to verify my account

- projects/client/src/App.jsx
- projects/server/src/controllers/userControllers.js
Fixing phone number
Fixing branch id
> [OGWA-12-FIX#2]

- projects/client/src/views/Checkout/components/order.jsx
- projects/client/src/views/Profile/components/addressesTab.jsx
- projects/client/src/views/Report/components/chartReport.jsx
- projects/client/src/views/Report/components/table/tableFilter.jsx
- projects/client/src/views/Report/components/table/tableReport.jsx
- projects/client/src/views/Report/pages/report.jsx
- projects/server/src/controllers/reportControllers.js
- projects/server/src/controllers/userControllers.js
- projects/server/src/routers/reportRouters.js
- projects/server/src/templates/resetPassword.html
- projects/server/src/templates/templateVerification.html
bug fixing
env for email template
> [OGWA-45-FIX]

- projects/server/src/models/Products.js
- projects/server/src/models/Stocks.js
- projects/server/src/models/branches.js
* [OGWA-38] Models association fix
> [OGWA-38] Models association fix (#105)

- projects/server/src/models/Products.js
- projects/server/src/models/Stocks.js
* [OGWA-38] Models association fix
> [OGWA-38] Models association fix (#107)

- projects/server/src/config/config.js
- projects/server/src/models/Users.js
- projects/server/src/models/Vouchers.js
* [OGWA-38] Responsive adjustments
* [OGWA-38] Deploy v.2.2.
> Deploy v.2.2. 

- projects/server/src/controllers/productReportControllers.js
- projects/server/src/models/Products.js
- projects/server/src/models/branches.js
> Deploy v.3.3

- package-lock.json
- projects/server/package.json
- projects/server/src/models/Products.js
- projects/server/src/models/branches.js
> Deploy v.3.7

- projects/server/src/controllers/productReportControllers.js
- projects/server/src/models/Users.js
> Deploy v.4.0.1

- projects/client/src/pages/stockReport.jsx
- projects/server/src/controllers/productReportControllers.js
- projects/server/src/models/Products.js
- projects/server/src/models/Users.js
- projects/server/src/models/Vouchers.js
- projects/server/src/models/branches.js
Pending Deploy Action To Linode
> Deploy v.4.1 (#160) Ready For Hosting On Linode

- projects/client/src/views/Profile/components/profileField/phoneField.jsx
- projects/client/src/views/Register/components/registerField.jsx
- projects/client/src/views/Report/components/table/pagination.jsx
yup phone and pagination for report
> Deploy bug fixing

- projects/client/src/pages/stockReport.jsx
- projects/server/src/controllers/productControllers.js
- projects/server/src/controllers/productReportControllers.js
> Deploy v.5.3.a (Debug API Endpoint)

- projects/client/src/pages/stockReport.jsx
- projects/server/src/controllers/productControllers.js
- projects/server/src/controllers/productReportControllers.js
* Alpha Release V.5.1
* Merge Sync v.5.1.a to OGWA-38
* Deploy v.5.3.2.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
> Deploy v.5.3.2.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)

- projects/client/src/pages/stockReport.jsx
- projects/server/src/controllers/productControllers.js
- projects/server/src/controllers/productReportControllers.js
* Alpha Release V.5.1
* Merge Sync v.5.1.a to OGWA-38
* Deploy v.5.3.2.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.3.3.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
> Deploy v.5.3.3.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)

- projects/server/src/controllers/productControllers.js
- projects/server/src/controllers/productReportControllers.js
- projects/server/src/controllers/reportControllers.js
* Alpha Release V.5.1
* Merge Sync v.5.1.a to OGWA-38
* Deploy v.5.3.3.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.3.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
> Deploy v.5.3.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization) (#208)

- projects/client/src/pages/stockReport.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ActionButton/confirmButtonOrder.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ActionButton/uploadButtonOrder.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ModalProcessing/detailOrderModal.jsx
- projects/client/src/views/OrdersList/components/branchOrder/allOrders.jsx
- projects/client/src/views/OrdersList/components/branchOrder/pending.jsx
- projects/client/src/views/OrdersList/components/branchOrder/processing.jsx
- projects/client/src/views/OrdersList/components/branchOrder/received.jsx
- projects/client/src/views/OrdersList/components/branchOrder/sent.jsx
- projects/client/src/views/OrdersList/components/branchOrder/waiting.jsx
- projects/client/src/views/OrdersList/components/superAdminOrderList.jsx
- projects/client/src/views/OrdersList/components/userOrdersList.jsx
- projects/client/src/views/Register/components/registerField.jsx
- projects/client/src/views/Register/index.jsx
- projects/server/src/controllers/productControllers.js
- projects/server/src/controllers/productReportControllers.js
- projects/server/src/controllers/reportControllers.js
* Alpha Release V.5.1
* Merge Sync v.5.1.a to OGWA-38
* Deploy v.5.3.3.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.3.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
> Deploy v.5.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)

- projects/client/src/pages/stockReport.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ActionButton/confirmButtonOrder.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ActionButton/uploadButtonOrder.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ModalProcessing/detailOrderModal.jsx
- projects/client/src/views/OrdersList/components/branchOrder/allOrders.jsx
- projects/client/src/views/OrdersList/components/branchOrder/pending.jsx
- projects/client/src/views/OrdersList/components/branchOrder/processing.jsx
- projects/client/src/views/OrdersList/components/branchOrder/received.jsx
- projects/client/src/views/OrdersList/components/branchOrder/sent.jsx
- projects/client/src/views/OrdersList/components/branchOrder/waiting.jsx
- projects/client/src/views/OrdersList/components/superAdminOrderList.jsx
- projects/client/src/views/OrdersList/components/userOrdersList.jsx
- projects/client/src/views/Register/components/registerField.jsx
- projects/client/src/views/Register/index.jsx
- projects/server/src/controllers/productControllers.js
- projects/server/src/controllers/productReportControllers.js
- projects/server/src/controllers/reportControllers.js
* Deploy v.3.7 (#147) -- sequelize update@latest v.6.33.0
* Deploy v.4.1 (#160) Ready For Hosting On Linode
* Deploy v.4.6 (LIVE)
* Deploy v.4.8 (API Adjustment -- serve static) (#181) (#182)
* Deploy v.5.0 SMTP & Handlebars Path Update + Hotfixes
* Deploy v.5.1.a (Clean Prod Stable Build) (#189)
* Alpha Release V.5.1 <sup>17/10/23</sup>
* Merge Sync v.5.1.a to OGWA-38 @asc33nzio base development branch
* Deploy v.5.3.3.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.3.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.4.a (Debug API Endpoint - Fixed Sequelize Literal Capitalization)
* Deploy v.5.5.a (Post Sequelize …
> Deploy v.5.5.a (Post Sequelize Hotfixes--Pre Beta Stability Test) (#213)

- projects/client/src/components/cart/add.jsx
- projects/client/src/pages/productDetail.jsx
- projects/client/src/views/Cart/components/card.jsx
- projects/client/src/views/Cart/components/receiptMobile.jsx
- projects/client/src/views/Cart/components/update.jsx
- projects/client/src/views/Cart/index.jsx
- projects/client/src/views/Checkout/components/order.jsx
- projects/client/src/views/Home/promo/components/card.jsx
- projects/client/src/views/OrdersList/components/branchOrder/ActionButton/uploadButtonOrder.jsx
- projects/client/src/views/OrdersList/components/cancel.jsx
- projects/client/src/views/OrdersList/components/uploadProof.jsx
- projects/server/src/controllers/cartControllers.js
- projects/server/src/controllers/discountControllers.js
- projects/server/src/controllers/orderControllers.js
- projects/server/src/routers/orderRouters.js
* Deploy v.3.7 (#147) -- sequelize update@latest v.6.33.0
* Deploy v.4.1 (#160) Ready For Hosting On Linode
* Deploy v.4.6 (**LIVE**-**LIVE**-**LIVE**)
* Deploy v.4.8 (API Adjustment -- serve static) (#181) (#182)
* Deploy v.5.0 SMTP & Handlebars Path Update + Hotfixes
* Deploy v.5.1.a (Clean Prod Stable Build) (#189)
* Alpha Release V.5.1 <sup>17/10/23</sup>
* Merge Sync v.5.1.a to OGWA-38: @asc33nzio 's base development branch
* Deploy v.5.3.3.a (Debug API Endpoint -- Fixed Sequelize Literal Capitalization)
* Deploy v.5.3.4.a (--__idem__--)
* Deploy v.5.4.a (--__idem__--)
* Deploy v.5.5.1.a (Debug Production Cart Issues)
* Deploy v.5.5.a (Post Sequelize Hotfixes--Pre Beta …
> Deploy v.5.5.1.a (Debug Production Cart Issues)

- projects/client/src/components/cart/add.jsx
- projects/client/src/views/Cart/components/receiptMobile.jsx
- projects/client/src/views/Checkout/components/order.jsx
- projects/server/src/controllers/cartControllers.js
* Deploy v.3.7 (#147) -- sequelize update@latest v.6.33.0
* Deploy v.4.1 (#160) Ready For Hosting On Linode
* Deploy v.4.6 (**LIVE**-**LIVE**-**LIVE**)
* Deploy v.4.8 (API Adjustment -- serve static) (#181) (#182)
* Deploy v.5.0 SMTP & Handlebars Path Update + Hotfixes
* Deploy v.5.1.a (Clean Prod Stable Build) (#189)
* Alpha Release V.5.1 <sup>17/10/23</sup>
* Merge Sync v.5.1.a to OGWA-38: @asc33nzio 's base development branch
* Deploy v.5.3.3.a (Debug API Endpoint -- Fixed Sequelize Literal Capitalization)
* Deploy v.5.3.4.a (--__idem__--)
* Deploy v.5.4.a (--__idem__--)
* Deploy v.5.5.1.a (Debug Production Cart Issues)
* Deploy v.5.5.a (Post Sequelize Hotfixes--Pre Beta …
> Deploy v.5.6.a (Debug Production Cart Issues) #222
